create table if not exists staff
(
    id       bigint generated by default as identity
        constraint staff_pk
            primary key,
    name     varchar(100)         not null
        constraint staff_name_key
            unique,
    username varchar(30)          not null
        constraint staff_username_key
            unique,
    password varchar              not null,
    dob      timestamp            not null
        constraint staff_dob_check
            check (dob < now()),
    role     varchar(20)          not null,
    post     varchar(60)          not null,
    enabled  boolean default true not null
);

alter table staff
    owner to postgres;

create unique index staff_id_uindex
    on staff (id);

INSERT INTO public.staff (id, name, username, password, dob, role, post, enabled) VALUES (2, 'Jonh Doe Jn.', 'admin', '$2a$10$ZbbHr8RcbxHpO9fjUaQmfOUJYmsdME7Ov0qrxgYmY30AX93/hVchW', '1998-09-27 00:00:00.000000', 'ROLE_ADMIN', 'Administrator of clinic', true);
INSERT INTO public.staff (id, name, username, password, dob, role, post, enabled) VALUES (7, 'Sara Mrgjnkevitch', 'sara', '$2a$10$SNwkyvxJCv2Hkkc0wv.mzOYkat0HXmiZv3V8Ba8grXvSv0iHpcOBK', '2000-11-06 00:00:00.000000', 'ROLE_NURSE', 'Assistant of cat hugger expert', true);
INSERT INTO public.staff (id, name, username, password, dob, role, post, enabled) VALUES (6, 'Thomas White', 'thomas', '$2a$10$7zPrtgvU0UlyF.iiUgUpM.Rs3YxvPVcopEmyCNOejx2MUzr.DW5h6', '2002-02-01 00:00:00.000000', 'ROLE_DOCTOR', 'Cat hugger expert', true);
INSERT INTO public.staff (id, name, username, password, dob, role, post, enabled) VALUES (8, 'Test user', 'user', '$2a$10$TokXopa49VeNUY2S9eErK.qjabR9Fp52mONlbBAcrF34M.DoWRsNi', '2022-10-01 00:00:00.000000', 'ROLE_NURSE', 'test', false);

create table if not exists client
(
    id         bigint generated by default as identity
        constraint client_pk
            primary key,
    name       varchar(100) not null
        constraint client_name_key
            unique,
    dob        timestamp    not null
        constraint client_dob_check
            check (dob < now()),
    address    varchar,
    email      varchar(100)
        constraint client_email_key
            unique,
    phone      varchar(16)  not null,
    created_at timestamp    not null,
    updated_at timestamp    not null,
    created_by varchar(100) not null,
    updated_by varchar(100) not null
);

alter table client
    owner to postgres;

create unique index client_id_uindex
    on client (id);

create unique index client_phone_uindex
    on client (phone);

INSERT INTO public.client (id, name, dob, address, email, phone, created_at, updated_at, created_by, updated_by) VALUES (1, 'Tom Reddle', '2022-10-01 00:00:00.000000', '', 'Tom@gmail.com', '+7(999)123-45-67', '2022-10-26 17:08:37.483000', '2022-10-26 17:08:37.483000', 'Thomas White', 'Thomas White');
INSERT INTO public.client (id, name, dob, address, email, phone, created_at, updated_at, created_by, updated_by) VALUES (2, 'Sam Fisher', '2022-10-07 00:00:00.000000', 'Red Square, d. 23', 'Sam@a', '+7(123)456-78-90', '2022-10-27 11:45:58.406000', '2022-10-27 11:45:58.406000', 'Jonh Doe Jn.', 'Jonh Doe Jn.');

create table if not exists cat
(
    id         bigint generated by default as identity
        constraint cat_pk
            primary key,
    owner      bigint          not null
        constraint cat_owner_fkey
            references client
            on delete set null,
    name       varchar(100)     not null,
    dob        timestamp        not null
        constraint cat_dob_check
            check (dob < now()),
    color      varchar(50)      not null,
    weight     double precision not null
        constraint cat_weight_check
            check ((weight > (0)::double precision) AND (weight <= (30)::double precision)),
    created_at timestamp        not null,
    updated_at timestamp        not null,
    created_by varchar(100)     not null,
    updated_by varchar(100)     not null
);

alter table cat
    owner to postgres;

create unique index cat_id_uindex
    on cat (id);

INSERT INTO public.cat (id, owner, name, dob, color, weight, created_at, updated_at, created_by, updated_by) VALUES (1, 1, 'Fluffy', '2022-10-01 00:00:00.000000', 'Black', 7.800000190734863, '2022-10-26 15:06:22.179000', '2022-10-26 15:06:22.179000', 'Thomas White', 'Thomas White');
INSERT INTO public.cat (id, owner, name, dob, color, weight, created_at, updated_at, created_by, updated_by) VALUES (7, 2, 'Рысь Путятишна', '2022-10-25 00:00:00.000000', 'камышовый в глупую крапинку', 4.5, '2022-10-26 20:31:02.220000', '2022-10-26 20:46:41.544000', 'Виктор Даценко', 'Jonh Doe Jn.');

create table if not exists medical_history
(
    id         bigint generated by default as identity
        constraint medical_history_pkey
            primary key,
    cat        bigint      not null
        constraint medical_history_cat_fkey
            references cat,
    date       timestamp    not null,
    symptoms   varchar      not null,
    diagnosis  varchar      not null,
    therapy    varchar      not null,
    outcome    varchar,
    created_by varchar(100) not null,
    updated_at timestamp    not null,
    updated_by varchar(100) not null
);

alter table medical_history
    owner to postgres;

INSERT INTO public.medical_history (id, cat, date, symptoms, diagnosis, therapy, outcome, created_by, updated_at, updated_by) VALUES (1, 1, '2022-10-26 19:54:42.176000', 'Grumpy face', 'Grumpyfacit', 'Hugs 3 times per day', 'Full recovery', 'Jonh Doe Jn.', '2022-10-26 20:25:19.334000', 'Jonh Doe Jn.');
INSERT INTO public.medical_history (id, cat, date, symptoms, diagnosis, therapy, outcome, created_by, updated_at, updated_by) VALUES (2, 7, '2022-10-26 20:31:34.091000', 'Писается, глупится', 'Депутат', 'Не давать взятки', '', 'Виктор Даценко', '2022-10-26 20:31:34.091000', 'Виктор Даценко');
INSERT INTO public.medical_history (id, cat, date, symptoms, diagnosis, therapy, outcome, created_by, updated_at, updated_by) VALUES (3, 7, '2022-10-26 20:51:14.801000', 'Испуганный вид', 'Пугливость', 'Лечению не поддается. Принять и простить', 'Безнадежна', 'Jonh Doe Jn.', '2022-10-26 20:51:14.801000', 'Jonh Doe Jn.');